- name: install required packages
  become: true
  package:
    state: present
    name:
      - weechat
      - python-pip
      - python-virtualenv
      - python-setuptools

- name: aur packages are installed
  include_tasks: build_package.yml
  loop:
    - name: libolm
      path: https://aur.archlinux.org/libolm.git

- name: build package exists
  become: true
  file:
    path: /opt/BUILD
    state: directory
    owner: tristan
    group: tristan

- name: weechat-matrix plugin is pulled and up to date
  become: true
  become_user: tristan
  git:
    repo: https://github.com/poljar/weechat-matrix.git
    dest: /opt/BUILD/weechat-matrix
  register: git

- name: old virtualenv is removed
  file:
    path: /home/tristan/.weechat/python/venv/
    state: absent
  when: git is changed

- name: virtualenv are installed and up to date
  become: true
  become_user: tristan
  pip:
    requirements: /opt/BUILD/weechat-matrix/requirements.txt
    virtualenv: /home/tristan/.weechat/python/venv
  when: git is changed

- name: weechat-matrix is installed
  become: true
  become_user: tristan
  make:
    chdir: /opt/BUILD/weechat-matrix/
    target: install
  when: git is changed
