- name: required packages are installed
  become: true
  package:
    name: "{{item}}"
    state: present
  loop:
    - curl
    - zsh
    - zsh-theme-powerlevel9k

- name: oh-my-zsh is installed
  become: true
  become_user: tristan
  shell: sh -c "$(curl -fsSL https://raw.githubusercontent.com/robbyrussell/oh-my-zsh/master/tools/install.sh)"
  args:
    chdir: /home/tristan/
    creates: /home/tristan/.oh-my-zsh/

- name: configuration file is copied
  template:
    src: zshrc
    dest: /home/tristan/.zshrc
    owner: tristan
    group: tristan
