- name: required packages are installed
  become: true
  package:
    state: present
    name:
      - curl
      - zsh

- name: oh-my-zsh is installed
  become: true
  become_user: tristan
  shell: sh -c "$(curl -fsSL https://raw.githubusercontent.com/robbyrussell/oh-my-zsh/master/tools/install.sh)"
  args:
    chdir: /home/tristan/
    creates: /home/tristan/.oh-my-zsh/

- name: configuration file is copied
  copy:
    src: zshrc
    dest: /home/tristan/.zshrc
    owner: tristan
    group: tristan

- name: powerlevel10k theme is installed
  become_user: tristan
  become: true
  git:
    depth: 1
    repo: https://github.com/romkatv/powerlevel10k.git
    dest: /home/tristan/.oh-my-zsh/custom/themes/powerlevel10k
