- name: packages are installed
  package:
    state: present
    name:
      - wpa_supplicant
      - iw
      - connman

- name: aur packages are installed
  include_tasks: build_package.yml
  loop:
    - name: nordvpn-bin
      path: https://aur.archlinux.org/nordvpn-bin.git

- name: enable network services
  service:
    name: connman.service
    enabled: true
