- name: packages are installed
  package:
    name: "{{ item }}"
    state: present
  loop:
    - connman
    - wpa_supplicant

- name: aur packages are installed
  include: build_package.yml package={{ item }}
  loop:
    - name: nordvpn-bin
      path: https://aur.archlinux.org/nordvpn-bin.git

- name: enable net services
  service:
    name: "{{ item }}"
    enabled: true
  loop:
    - connman.service
    - nordvpnsd.service

- name: enable user scoped nordvpn service
  become: true
  become_user: tristan
  systemd:
    name: nordvpnud.service
    enabled: true
    state: started
    scope: user
