- name: packages are installed
  become: true
  package:
    state: present
    name:
      - wpa_supplicant
      - iw
      - networkmanager
      - gnu-netcat

- name: enable network services
  become: true
  service:
    name: NetworkManager.service
    enabled: true
