- name: packages are installed
  package:
    state: present
    name:
      - wpa_supplicant
      - iw
      - connman

- name: enable network services
  service:
    name: connman.service
    enabled: true
