- name: packages are installed
  package:
    name: "{{ item }}"
    state: present
  loop:
    - wpa_supplicant
    - iw
    - connman

- name: aur packages are installed
  include_tasks: build_package.yml
  loop:
    - name: nordvpn-bin
      path: https://aur.archlinux.org/nordvpn-bin.git

- name: enable network services
  service:
    name: "{{ item }}"
    enabled: true
  loop:
    - connman.service
    - nordvpnsd.service

- name: enable user scoped nordvpn service
  become: true
  become_user: tristan
  systemd:
    name: nordvpnud.service
    enabled: true
    state: started
    scope: user
