- name: desktop package are installed
  become: true
  package:
    state: present
    name:
      - curl
      - tree
      - alsa-utils
      - pulseaudio
      - pulseaudio-alsa
      - keepassxc
      - feh
      - sshpass
      - ranger
      - exfat-utils
      - unzip
      - detox
      - pandoc
      - ttf-dejavu
      - grim
      - screenfetch
      - virtualbox
      - virtualbox-host-modules-arch
      - nextcloud-client
      - cmake
      - qt5-base
      - qtcreator
      - gimp
      - evince
      - julia
      - jre8-openjdk
      - obs-studio
      - vlc

- name: aur packages are installed
  include_tasks: build_package.yml
  loop:
    - name: minecraft
      path: https://aur.archlinux.org/minecraft-launcher.git
    - name: termite-nocsd
      path: https://aur.archlinux.org/termite-nocsd.git
    - name: wf-recorder-git
      path: https://aur.archlinux.org/wf-recorder-git.git
    - name: ganttproject
      path: https://aur.archlinux.org/ganttproject.git
    - name: gomuks-git
      path: https://aur.archlinux.org/gomuks-git.git
    - name: teams
      path: https://aur.archlinux.org/teams.git
    - name: slack-desktop
      path: https://aur.archlinux.org/slack-desktop.git

- name: termite config dir exists
  file:
    path: /home/tristan/.config/termite
    state: directory
    owner: tristan
    group: tristan

- name: termite configuration files are copied
  copy:
    src: termite
    dest: /home/tristan/.config/termite/config
    owner: tristan
    group: tristan

- name: directory for vms is created
  become: true
  file:
    path: /var/virtualbox-vms
    state: directory
    owner: tristan
    group: tristan

- name: asciidoctor required packages
  become: true
  package:
    state: absent
    name: asciidoctor

- name: install asciidoctor-pdf
  gem:
    name: asciidoctor-pdf
    state: present
    pre_release: true

- name: install extentions gems
  gem:
    name: "{{ item }}"
    state: present
  loop:
    #- rouge
    #- pygments.rb
    #- coderay
    - asciidoctor-diagram
