- name: a specific user is present to build aur packages
  become: true
  user:
    name: aur_builder
    create_home: false

- name: the aur_builder specific user as suffisent rights
  become: true
  lineinfile:
    path: /etc/sudoers.d/11-aur_builder
    line: 'aur_builder ALL=(ALL) NOPASSWD: /usr/bin/pacman'
    create: yes
    validate: 'visudo -cf %s'

- name: ansible-aur plugin is installed
  git:
    repo: https://github.com/kewlfft/ansible-aur.git
    dest: ~/.ansible/plugins/modules/aur

- name: the AUR directory is created
  file:
    path: /opt/AUR
    state: directory
    owner: aur_builder

