- name: a specific user is present to build aur packages
  user: name=aur_builder

- name: the aur_builder specific user as suffisent rights
  lineinfile:
     path: /etc/sudoers.d/aur_builder-allow-to-sudo-pacman
     state: present
     line: "aur_builder ALL=(ALL) NOPASSWD: /usr/bin/pacman"
     validate: /usr/sbin/visudo -cf %s
     create: yes

- name: ansible-aur plugin is installed
  git:
    repo: https://github.com/kewlfft/ansible-aur.git
    dest: ~/.ansible/plugins/modules/aur

- name: the AUR directory is created
  file:
    path: "{{ aur_path }}"
    state: directory
    owner: aur_builder

- name: aur packages are installed
  become: yes
  become_user: aur_builder
  aur:
    name: "{{ item }}"
    use: makepkg
  loop: "{{ aur_packages }}"

#- name: aur packages are pulled
#  become: true
#  become_user: aur_builder
#  git:
#    repo: "{{ item.path }}"
#    dest: "{{ aur_path }}/{{ item.name }}"
#  loop: "{{ aur_packages }}"
#
#- name: aur packages are built
#  become: true
#  become_user: aur_builder
#  command: "chdir={{ aur_path }}/{{ item.name }} makepkg -si"
#  loop: "{{ aur_packages }}"
