- name: packages are installed
  package:
    state: present
    name: 
      - sway
      - swayidle
      - swaylock
      - dmenu
      - waybar
      - otf-font-awesome

- name: config directories exists
  file:
    path: "/home/tristan/.config/{{ item }}"
    state: directory
    owner: tristan
    group: tristan
  loop:
    - waybar
    - sway

- name: configuration files are copied
  copy:
    src: "{{ item.name }}"
    dest: "/home/tristan/.config/{{ item.dest }}"
    owner: tristan
    group: tristan
  loop:
    - { name: sway, dest: sway/config }
    - { name: waybar.css, dest: waybar/style.css }

- name: aur packages are installed
  include_tasks: build_package.yml
  loop:
    - name: swaylock-blur-bin
      path: https://aur.archlinux.org/swaylock-blur-bin.git

- name: wallpapers are copied
  copy:
    src: wallpapers/
    dest: /home/tristan/Pictures/wallpapers/
    owner: tristan
    group: tristan
