- name: user tristan is created
  user:
    name: tristan
    groups: docker
    shell: /bin/zsh

- name: directory for vms is created
  file:
    path: /var/virtualbox-vms
    state: directory
    owner: tristan
    group: tristan

- name: routine package are installed
  package:
    name: "{{ item }}"
    state: present
  loop:
    - alsa-utils
    - pulseaudio
    - pulseaudio-alsa
    - keepassxc
    - nextcloud-client
    - docker
    - docker-compose
    - ttf-dejavu
    - thunderbird
    - thunderbird-extension-enigmail
    - openssh
    - grim
    - screenfetch
    - feh
    - virtualbox-host-modules-arch
    - sshpass
    - ranger
    - exfat-utils
      #- qemu-headless
      #- libvirt
      #- virt-install
      #- virt-viewer

- name: aur packages are installed
  include: build_package.yml package={{ item }}
  loop:
    - name: brave-bin
      path: https://aur.archlinux.org/brave-bin.git
