- name: routine package are installed
  become: true
  package:
    state: present
    name:
      - curl
      - tree
      - keepassxc
      - docker
      - docker-compose
      - thunderbird
      - feh
      - sshpass
      - ranger
      - exfat-utils
      - unzip
      - detox
      - profanity
      - pandoc

- name: distrib specific packages are installed
  include_tasks: "{{ DISTRIB }}.yml"

- name: user tristan is created
  become: true
  user:
    name: tristan
    groups:
      - docker
      - wheel
    shell: /bin/zsh

- name: directory for vms is created
  become: true
  file:
    path: /var/virtualbox-vms
    state: directory
    owner: tristan
    group: tristan

# TODO : update la conf ssh pour strict host key
