- name: user tristan is created
  user:
    name: tristan
    groups: docker
    shell: /bin/zsh

- name: routine package are installed
  package:
    name: "{{ item }}"
    state: present
  loop:
    - alsa-utils
    - pulseaudio
    - pulseaudio-alsa
    - keepassxc
    - nextcloud-client
    - docker
    - docker-compose
    - ttf-dejavu
    - thunderbird
    - thunderbird-extension-enigmail
    - openssh
    - grim
    - screenfetch
    - feh
    - virtualbox-host-modules-arch
    - sshpass
    - ranger
      #- qemu-headless
      #- libvirt
      #- virt-install
      #- virt-viewer

