- name: user tristan is created
  user:
    name: tristan
    groups: docker
    shell: /bin/zsh

- name: routine package are installed
  package:
    name: "{{ item }}"
    state: present
  loop:
    - keepassxc
    - nextcloud-client
    - docker
    - docker-compose
    - connman
    - dmenu
    - wpa_supplicant
    - ttf-dejavu
    - thunderbird
    - thunderbird-extension-enigmail
    - openssh
    - zsh
    - zsh-theme-powerlevel9k
    - qtcreator

- name: enable connman
  service:
      name: connman.service
      enabled: true
