- name: are installed
  package:
    name: "{{ item }}"
    state: present
  loop:
    - zsh
    - zsh-theme-powerlevel9k

- name: aur packages are installed
  include: build_package.yml package={{ item }}
  loop:
    - name: termite-nocsd
      path: https://aur.archlinux.org/termite-nocsd.git

- name: configuration files are copied
  copy:
    src: "{{ item.filename }}"
    dest: "{{ item.dest }}"
    owner: tristan
    group: tristan
  loop:
    - { filename: zshrc, dest: /home/tristan/.zshrc }
    - { filename: termite, dest: /home/tristan/.config/termite/config }

- name: oh-my-zsh is installed
  become: true
  become_user: tristan
  shell: sh -c "$(curl -fsSL https://raw.githubusercontent.com/robbyrussell/oh-my-zsh/master/tools/install.sh)"
  args:
    chdir: /home/tristan/
    creates: /home/tristan/.oh-my-zsh/
