- name: aur packages are installed
  include_tasks: build_package.yml
  loop:
    - name: termite-nocsd
      path: https://aur.archlinux.org/termite-nocsd.git

- name: configuration files are copied
  copy:
    src: termite
    dest: /home/tristan/.config/termite/config
    owner: tristan
    group: tristan
