- name: the lab file structure is created
  file:
    state: directory
    path: "{{ item }}"
  loop:
    - /home/tristan/SECLAB
    - /home/tristan/SECLAB/dictionaries
    - /home/tristan/SECLAB/ctfs
    - /home/tristan/SECLAB/ctfs/hacker101

- name: packages dependencies are satisfied
  package:
      name: git go dep
      state: present

- name: aur packages are installed
  include_tasks: build_package.yml
  loop:
    - name: dirstalk
      path: https://aur.archlinux.org/dirstalk-git.git

- name: dictionaries are pulled
  get_url:
    url: "https://raw.githubusercontent.com/dustyfresh/dictionaries/master/DirBuster-Lists/{{ item }}"
    dest: /home/tristan/SECLAB/dictionaries/
  loop:
    - apache-user-enum-1.0.txt
    - apache-user-enum-2.0.txt
    - directory-list-1.0.txt
    - directory-list-2.3-big.txt
    - directory-list-2.3-medium.txt
    - directory-list-2.3-small.txt
    - directory-list-lowercase-2.3-big.txt
    - directory-list-lowercase-2.3-medium.txt
    - directory-list-lowercase-2.3-small.txt
