- name: required packages are installed
  package:
    name: autopep8
    state: present

- name: vimrc file exists
  file:
    path: /home/tristan/.vimrc
    state: touch

- name: vim awesome is pulled and up to date
  become: true
  become_user: tristan
  git:
    repo: https://github.com/amix/vimrc.git
    dest: /home/tristan/.vim_runtime
    depth: 1

- name: check if vimawesome has been installed
  lineinfile:
    name: /home/tristan/.vimrc
    line: "set runtimepath+=~/.vim_runtime"
    state: present
  check_mode: yes
  register: vimrc

- name: vim awesome is installed
  become: true
  become_user: tristan
  command: sh /home/tristan/.vim_runtime/install_awesome_vimrc.sh
  when: vimrc is changed

- name: personal configuration file is copied
  copy:
    src: vimrc
    dest: /home/tristan/.vim_runtime/my_configs.vim
    owner: tristan
    group: tristan

- name: install vim modules
  become: true
  become_user: tristan
  git:
    repo: "{{ item.repo }}"
    dest: "{{ item.dest }}"
  loop:
    - { repo: "https://github.com/bfrg/vim-cpp-modern.git", dest: "/home/tristan/.vim_runtime/my_plugins/vim-cpp-modern" }
    - { repo: "https://github.com/rhysd/vim-clang-format.git", dest: "/home/tristan/.vim_runtime/my_plugins/vim-clang-format" }
    - { repo: "https://github.com/tell-k/vim-autopep8.git", dest: "/home/tristan/.vim_runtime/my_plugins/vim-autopep8" }
    - { repo: "https://github.com/posva/vim-vue.git", dest: "/home/tristan/.vim_runtime/my_plugins/vim-vuejs" }
    - { repo: "https://github.com/hashivim/vim-terraform.git", dest: "/home/tristan/.vim_runtime/my_plugins/vim-terraform" }
    - { repo: "https://github.com/andreshazard/vim-freemarker.git", dest: "/home/tristan/.vim_runtime/my_plugins/vim-freemarker" }
