- name: neovim is installed
  package:
    name: neovim
    state: present

- name: aur packages are installed
  include_tasks: build_package.yml
  loop:
    - name: neovim-plug
      path: https://aur.archlinux.org/neovim-plug.git

- name: neovim configuration is copied
  copy:
    src: init.vim
    dest: /home/tristan/.config/nvim/init.vim

- name: pip packages are installed
  pip:
    name: pynvim
    extra_args: --user
