- name: neovim is installed
  package:
    name:
      - neovim
      - python-pynvim

- name: aur packages are installed
  include_tasks: build_package.yml
  loop:
    - name: neovim-plug
      path: https://aur.archlinux.org/neovim-plug.git

- name: neovim configuration is copied
  copy:
    src: init.vim
    dest: /home/tristan/.config/nvim/init.vim
